# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(help_text='Qual o ativo voce quer analisar? Exemplo: petr4 para analisar Petrobras', max_length=10)),
                ('email', models.EmailField(help_text='Qual o seu e-mail?', max_length=200)),
                ('Seu_nome', models.CharField(help_text='Qual o seu nome?', max_length=200)),
                ('Dicas', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], help_text='Gostaria de receber dicas de Investimento?', max_length=12)),
            ],
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
