# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-31 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='COGS',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='input',
            name='Expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='input',
            name='Net_Sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='input',
            name='PMP',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='input',
            name='PMR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10000),
        ),
    ]
