# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180531_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='COGS',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Custos dos produtos vendidos | utilizar formato americano', max_digits=10000),
        ),
        migrations.AlterField(
            model_name='input',
            name='Empresa',
            field=models.CharField(help_text='Informe o nome fantasia da sua empresa', max_length=50),
        ),
        migrations.AlterField(
            model_name='input',
            name='Expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Despesas Operacionais | utilizar formato americano', max_digits=10000),
        ),
        migrations.AlterField(
            model_name='input',
            name='Net_Sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Vendas Liquidas de Impostos | utilizar formato americano', max_digits=10000),
        ),
        migrations.AlterField(
            model_name='input',
            name='PMP',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Insira o Prazo Medio de Pagamentos | utilizar formato americano', max_digits=10000),
        ),
        migrations.AlterField(
            model_name='input',
            name='PMR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Insira o Prazo Medio de Recebimentos | utilizar formato americano', max_digits=10000),
        ),
    ]
